os: Visual Studio 2015
platform: x64
clone_folder: C:\rpcs3
clone_depth: 3

before_build:
  - DownloadFile http://releases.llvm.org/5.0.0/llvm-5.0.0.src.tar.xz
  - 7z x llvm-5.0.0.src.tar.xz
  - 7z x llvm-5.0.0.src.tar
  - move llvm-5.0.0.src llvm
  - mkdir llvm_build
  - cd llvm_build
  - cmake -G "Visual Studio 14 Win64" ../llvm -DCMAKE_BUILD_TYPE=Release
  - dir
  
  
